kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: interface
  image: plugins/docker
  build_args:
      - APP_ENV=production
  settings:
    repo: registry.curriculo.jurema.la/interface
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    registry: registry.curriculo.jurema.la
    dockerfile: ./interface/Dockerfile
    context: ./interface


